name: 'Run All Tests'

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"
  push:
    branches:
      - cucumber
      - mocha
  pull_request:

env:
  CI: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.x
          cache: 'yarn' 

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Publish test report
        run: npx github-actions-ctrf reports/ctrf-report.json
        if: always()